set(rqt_offloading_controls_SETUP_PY_VERSION "0.0.0")
set(rqt_offloading_controls_SETUP_PY_SCRIPTS "")
set(rqt_offloading_controls_SETUP_PY_PACKAGES "rqt_offloading_controls")
set(rqt_offloading_controls_SETUP_PY_PACKAGE_DIRS "src/rqt_offloading_controls")
set(rqt_offloading_controls_SETUP_PY_MODULES "")
set(rqt_offloading_controls_SETUP_PY_MODULE_DIRS "")